README.md
src/main.rs
src/view.rs
tmux-thumbs.sh

Add an option to enable a "full" hint where the hint letter is surrounded by square brackets (for example `[a]` rather than `a`). This is the equivalent to the following `tmux-fingers` configuration option [1] and is useful to make the hint more visible:
```
set -g @fingers-compact-hints 0
```
[1] - https://github.com/Morantron/tmux-fingers#fingers-compact-hints
Signed-off-by: James O. D. Hunt <jamesodhunt@gmail.com>

view: Add @thumbs-contrast option

---

tmux-thumbs.sh

Previously, when setting the `--command` option to `tmux set-buffer {}`, it
will be interpreted by the `tmux-thumbs` binary as 4 separate args:
`--command`, `'tmux`, `set-buffer`, and `{}'`. This commit fixes it such that
the option will be correctly interpreted as a single arg.

Fixes passing options with spaces in the value

---

README.md
src/main.rs

Improve flexibility in `command` and `upcase-command` replacing `{}`
with the selected hint.

Fix command and paste command arguments

---

README.md
src/main.rs

Before this commit `command` and `upcase_command` where executed if you
pressed an uppercase key. This can force the user to have a innocuous
lower case command if they want to execute together.
Now they can be totally independent.

Exclusive commands

---

.github/workflows/rust.yml
.rustfmt.toml
.travis.yml
Cargo.lock
Cargo.toml
README.md
samples/test1
src/alphabets.rs
src/colors.rs
src/main.rs
src/state.rs
src/swapper.rs
src/view.rs

Tmux-thumbs has been using `rustbox` underneath since the first days. It was a convenient library at that moment but due the fact that some users are getting compilation errors and the fact that the library seems to not get updates, I decided to replace it with `termion`. It delivers the same functionality and it has nice documentation too.
This pull request also includes:

Replace rustbox with termion

---

tmux-thumbs.tmux

This change allows me to bind a prefix-less shortcut for @thumbs-key.
For example, I bind a prefix-less Alt+Shift+U instead of Prefix + Space:
set -g @thumbs-key '-n M-U'

let user specify a prefix-less @thumbs-key binding

---

README.md
src/swapper.rs

The regular expression describing the tmux user options expects to find
quotes around the value. However, in at least tmux 3.0a the
`show-options -g` command doesn't display quotes around the values,
which means the regex fails.
For example, the current regex will fail to find these user options:
$ tmux -V
tmux 3.0a
$ tmux show -g | grep -E "@thumbs"
@thumbs-bg-color default
@thumbs-fg-color green
@thumbs-hint-bg-color default
@thumbs-hint-fg-color blue
@thumbs-select-bg-color default
@thumbs-select-fg-color green
Make the quotes optional so that these options are picked up.
Fixes #33

swapper: Make quotes optional in key-value regex

---

src/view.rs

to address #47 
hits get marked on line 117, not on 92, it should be safe to do `line.to_string()'

remove line brackets from contrast

---

README.md
src/view.rs

This pull allows for positions to be offset from the match, so-as to not overwrite.
off_right will put it just to the right of the match, and off_left will put it to the left (overwriting the match if it would be off-screen)

Add additional position options

---

src/swapper.rs
tmux-thumbs.sh
tmux-thumbs.tmux

Copying a token with a quote in it was failing silently, and I briefly looked into why.
There were a few quoting issues in the scripts (most of them harmless, but easily fixed up: and I might have tinkered with it more than I needed to! Sorry!).
Then looking into how commands were executed and that *had* to be fixed: it's currently super dangerous. This changes the command construction from splicing the literal copied text to splicing in a bash variable reference (better, but not great). Reproducing the comment here:
----
The command we run has two arguments:
* The first arg is the (trimmed) text. This gets stored in a variable, in order to preserve quoting and special characters.
* The second argument is the user's command, with the `'{}'` token replaced with an unquoted reference to the …

Quoting fixes

---

README.md
src/swapper.rs

This is to address #56 
Alright, here is the problem. `\w+` does not match `\\` `[`, etc. Also it can be a valid requirement to match `"`, so it is just easier to treat whatever comes after `set -g @thumbs-regexp-N ` as the regexp that needs matching.
When not using any quotes or using double quotes, the user needs to define regexp with `\\`, when using single quotes, single `\` gets the job done.
In this case a regexp would look something like this:
```
set -g @thumbs-regexp-1 "Vlan\\d+"
```
or 
```
set -g @thumbs-regexp-1 'Vlan\d+'
```
or without quotes
```
set -g @thumbs-regexp-1 Vlan\\d+
```
When this gets passed to `tmux-thumbs` it'll read as `Vlan\\d+` which'll get passed to `thumbs` as `Vlan\\\\d+` thus it needs to be replaced.

fix regexp parsing from tmux config

---

Cargo.lock
Cargo.toml
src/view.rs

In my environment, when I execute tmux-thumb on a screen that displays Japanese characters, the character arrangement is broken.
I wrote a patch that fixes it.

Added support for wide characters such as cjk and emoji

---

Cargo.lock
Cargo.toml
README.md
src/colors.rs
src/main.rs
src/view.rs

This PR adds support for parsing hex colors, based on discussion in issue #65 
Feel free to suggest changes. My first few lines in Rust.

Add hex color support

---

src/view.rs

"thumbs mode" off:
"thumbs mode" on **without** this fix:
"thumbs mode" on **with** this fix:

Fix hint position when using contrast=1 and position off_left

---

README.md

I noticed two typos in the first _Usage_ paragraph.
Thank you for this awesome tool by the way! 😁

Fix two minor typos in README.md

---

README.md

On tmux 3.2, setting these options as directed in the old instructions
results in an "empty value" error message.

README: update guidance for thumbs-reverse and thumbs-unique

---

src/swapper.rs
tmux-thumbs.sh

multi-command related configuration is missing in current version.
This PR add this configuration:
* add "thumbs-multi-command" support
* add "thumbs-multi-bg-color" and "thumbs-multi-fg-color" support

add missing multi-command configuration of tmux mode

---

.github/workflows/release.yml

Adds a github action to build the rust binaries (using static linking to the musl library) for those who cannot build the rust dependency on their machines directly.

Add release workflow with musl static build

---

src/state.rs

Some `tmux-thumbs` users have asked to match paths with brackets on it,
because is a common pattern in NextJS or Remix.
Adding the test case and fixing the path regex.

Match complete paths with slugs

---

tmux-thumbs.sh

bbf677fda318 ("Improve the matrix of releases") included a fix to cope
with compiled and bundled installations.  However, the check for the
.git/ repository is done from where tmux is launched, not where
tmux-thumbs is installed, so RELEASE_DIR is not properly set always.
This leads to tmux-thumbs always trying to install itself when installed
via tmux-plugin-manager.

Fix installation bug in tag 0.7.0

---

tmux-thumbs-install.sh
tmux-thumbs.sh

Change the installation script so that the user can select whether to install from the existing compiled binaries or compiling with cargo.
- ~~Allow to pick the installation method on a non-interactive way.~~ I might try on a different PR.

Install from binary

---

README.md
tmux-thumbs-install.sh
tmux-thumbs.sh

If you update the plugin with TPM, the `thumbs` binary can get out of
sync. So we need to check the version before proceed.
If there is a version mismatch, then we run a new install in "update"
mode.

Add a new flow to detect plugin updates

---

tmux-thumbs.sh

The different implementations of `grep` that exist in Linux and OpenBSD
makes the tmux-thumbs script to crash. Changing the command to be
compatible.

Changing grep check for OpenBSD compatibility

---

.github/workflows/rust.yml
src/state.rs

It is quite common in some web frameworks (NextJS, Remix) to define routes with `$` on them. Adding support for paths that represent those routes.

Support paths with $ symbols
